SRC_DIR=src
OUT_DIR=out
CLASS_DIR=$(SRC_DIR)/Classes
MAIN=Main.java
ANTLR4=antlr4/antlr-4.9.1-complete.jar

all: Classes

#Criação dos arquivos .class
Classes: AutoGeneratedCode
	javac -d $(CLASS_DIR) -cp $(ANTLR4) $(SRC_DIR)/*.java $(SRC_DIR)/$(MAIN)

#Codigo do Scanner+Parser
AutoGeneratedCode:
	java -jar $(ANTLR4) $(SRC_DIR)/Arithmetic.g4

clean:
	rm -rf $(CLASS_DIR)

run:
	java -cp $(CLASS_DIR):$(ANTLR4) Main